<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>fbfc0a9a-a84c-42e7-ba1e-3ab91e10fb57</testSuiteGuid>
   <testCaseLink>
      <guid>fe872af7-5060-4bc5-b8f4-bacaaf4df8a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>'234'</defaultValue>
         <description></description>
         <id>47f3d7fe-e47f-4634-b3ca-4ea0b444e1cc</id>
         <masked>false</masked>
         <name>Street</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Trademark_Registration/D</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b9c751a6-1914-4b93-9885-fb1b1332ab15</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/NT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b9c751a6-1914-4b93-9885-fb1b1332ab15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Street</value>
         <variableId>47f3d7fe-e47f-4634-b3ca-4ea0b444e1cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b9c751a6-1914-4b93-9885-fb1b1332ab15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>City</value>
         <variableId>0f662d62-a523-4156-863b-10c2fe050b55</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
