<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_START</name>
   <tag></tag>
   <elementGuidId>aa394cc1-d4d5-435b-bcaf-67ca8c5b0e9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnStart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnStart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3480a3e8-ee8c-4061-aaa2-6ecba71fe08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnStart</value>
      <webElementGuid>ce07a978-e4ad-46b5-91dc-0e3082e40739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnStart</value>
      <webElementGuid>447d0057-24bf-41e5-855b-50c67a33aa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6011f839-c9bd-42b5-8bc5-0518773f7423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab8fe73d-7e65-4b89-95cd-005ebbaec73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href ='/Registration/Home/Trademark' </value>
      <webElementGuid>78ad6f8c-9de2-4857-8b96-907035323fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>START</value>
      <webElementGuid>968151ff-480b-4f1d-a961-6bb595e5db5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnStart&quot;)</value>
      <webElementGuid>7e8635b5-257a-44d5-a62b-0a44d2d53e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnStart']</value>
      <webElementGuid>05bb59bc-ff63-44ec-b235-e492cf8e65a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='column1']/div/div[6]/div/button</value>
      <webElementGuid>be1b980e-eb22-426a-899c-fe3a25086431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='START'])[1]/following::button[1]</value>
      <webElementGuid>f7ccdb28-98bd-4ed4-af29-89c4d1c4ae4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='click on the Start button below.'])[1]/following::button[1]</value>
      <webElementGuid>5663a5c3-c3b4-42e0-b9d9-be7036da2576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modification of Registration'])[1]/preceding::button[1]</value>
      <webElementGuid>ac089471-e625-4fe2-8baa-6bf2c290a1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment of Trademark/Service Mark (TM-108)'])[1]/preceding::button[1]</value>
      <webElementGuid>0e346ad6-bc4c-4fd2-9bec-c4087954fd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>921719e4-dd4e-49fa-8f29-38ceb443ee20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnStart' and @name = 'btnStart' and @type = 'submit' and (text() = 'START' or . = 'START')]</value>
      <webElementGuid>74c1f0d2-e07e-4e83-ad0b-f06f71ebdde0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
