<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_pYour browser does not support iframes. Please update your browser.p</name>
   <tag></tag>
   <elementGuidId>b75c7b87-f146-4a76-afe7-defa485e8ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ts-iframe']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>17abeedb-bc8f-4a6c-a288-3bce74c5ae6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>957127d7-53d5-4f5c-a957-688eadd7f01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>040f89d6-42a7-419a-9cdc-a3684f0a94be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f635fadd-1167-4692-8623-867abd2bc290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>javascript: $('#preloader').hide();</value>
      <webElementGuid>624dd504-0f42-4d6d-be9c-618426a409a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sos.preprod.simpligov.com/preprod/Portal/ShowWorkFlow/AnonymousEmbed/d23d2199-dd9b-4bef-9f37-ce39a02fd800</value>
      <webElementGuid>487299f3-ec63-465c-9138-844938b0e2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>524e06ca1fbdb5b22a4cdfad444e4f31</value>
      <webElementGuid>74f463c9-c62a-469c-9d52-94f0a1181e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        &lt;p>Your browser does not support iframes. Please update your browser.&lt;/p>
    </value>
      <webElementGuid>fd57cc58-4b09-4c83-a130-89acd294ee87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ts-iframe&quot;)/iframe[1]</value>
      <webElementGuid>faa598d0-9337-4edb-aab1-a160fa1b9a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ts-iframe']/iframe</value>
      <webElementGuid>9e7c7288-a5c7-47ba-8c27-258a810c0e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::iframe[1]</value>
      <webElementGuid>ceecffc2-f52e-4926-8dbc-cba732fa74d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/following::iframe[1]</value>
      <webElementGuid>0fefad21-a693-400d-811e-85361eb8c86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show or Hide'])[1]/preceding::iframe[1]</value>
      <webElementGuid>1a3622c8-6415-4f8e-8010-81f801cb0e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;p>Your browser does not support iframes. Please update your browser.&lt;/p>']/parent::*</value>
      <webElementGuid>594a94ee-9e5b-42d8-9276-ae065a140f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d4f4c906-c62a-4f3c-a0ed-50cd01332d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://sos.preprod.simpligov.com/preprod/Portal/ShowWorkFlow/AnonymousEmbed/d23d2199-dd9b-4bef-9f37-ce39a02fd800' and (text() = '
        &lt;p>Your browser does not support iframes. Please update your browser.&lt;/p>
    ' or . = '
        &lt;p>Your browser does not support iframes. Please update your browser.&lt;/p>
    ')]</value>
      <webElementGuid>ff412e91-08c2-4ca9-b73a-e351ce8fb877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
