<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_element474</name>
   <tag></tag>
   <elementGuidId>cb6e278e-b645-4da1-8c4d-90189abde263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element474_No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#element474_No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>501bb7c4-69f5-4b88-945c-948ed4e4b70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b2f56a73-f608-4385-8fe0-37afdb31cba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>153ec781-beb8-4739-8368-55a4b813bb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element474_No</value>
      <webElementGuid>9e549cc4-2530-47aa-a64b-a48cd21fba1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>element474</value>
      <webElementGuid>e86c401c-e741-41e0-9b4c-66f2194bf697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-name</name>
      <type>Main</type>
      <value>element474</value>
      <webElementGuid>0a6775dc-9afd-4197-8438-3203c889f8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withQTip toCheck form-element-wrapper radio-button no-align requiredCustom add-to-repository condition-trigger</value>
      <webElementGuid>6017c802-bcf2-4598-a3bb-a069d03ccfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>23.2</value>
      <webElementGuid>32744ea6-bdd9-4e6e-8da1-ed672b97f40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CalculateFormula(this);</value>
      <webElementGuid>c398c334-f46a-4518-b780-cd6de9b44fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9bf868b9-d6be-4e6e-bce3-5b47d746cd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d98ecaa-a877-42ef-b758-432df285f830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_tabindex</name>
      <type>Main</type>
      <value>23.2</value>
      <webElementGuid>74bfaeed-e8e6-44a8-8c4c-5de0aecf92e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element474_No&quot;)</value>
      <webElementGuid>2fc88c59-502e-4b77-a3a2-50a8f96290d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Trademark_istpageobjects/iframe_pYour browser does not support ifram_aa4ea2</value>
      <webElementGuid>d7c88a58-9380-4a47-a832-80855011003d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MAnualmodecapture/Trademark_istpageobjects/iframe_pYour browser does not support ifram_aa4ea2</value>
      <webElementGuid>4b430f23-6f8e-4d68-8dcd-50c380076817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element474_No']</value>
      <webElementGuid>a909342d-5273-4a1b-b3f2-fddb19778597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-element-wrapper_474']/div/div/div/fieldset/div[2]/div/input</value>
      <webElementGuid>21deaa1c-b1a7-4618-8ed0-ec19894239db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div/fieldset/div[2]/div/input</value>
      <webElementGuid>763a7d2e-845a-41a9-9c20-868bc67e0fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'element474_No' and @name = 'element474']</value>
      <webElementGuid>8a60885c-cd56-4856-9878-4eedb7655bbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
