<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trademark Frequently Asked Questions__b182ce</name>
   <tag></tag>
   <elementGuidId>7be33f28-6180-4a8a-9aec-e53b7605f145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='element2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;element2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbf7cd95-11e5-4999-a227-ef688a9e1c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-section-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bf717f59-fe99-4379-8f72-e5f31c6b5526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-section-next form-change-section</value>
      <webElementGuid>3d906a8d-421b-48c1-b8ad-7a6a22b3a9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c44fec58-ad36-43d7-a58e-5f086a2c37b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>26c619ce-0f8a-42d5-8412-441057d7f2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>element2</value>
      <webElementGuid>92a104e3-48c1-4d23-8be4-264f75213ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>32b777e2-6686-4fca-9654-5413572b8c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-section-0&quot;)/div[@class=&quot;form-section-buttons&quot;]/input[@class=&quot;form-section-next form-change-section&quot;]</value>
      <webElementGuid>571846af-75ac-49e7-9b6e-0aacbf5cc7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Trademark_istpageobjects/iframe_pYour browser does not support ifram_aa4ea2</value>
      <webElementGuid>870050f4-ce86-47ab-922d-6f006878be2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MAnualmodecapture/Trademark_istpageobjects/iframe_pYour browser does not support ifram_aa4ea2</value>
      <webElementGuid>8ca46bbd-af42-4b7f-8847-ed1d8418aaf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='element2']</value>
      <webElementGuid>1d22af93-98b3-40de-b67a-b13fd089ac9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-section-0']/div[6]/input</value>
      <webElementGuid>44e81550-1526-45e4-ad55-c4f5ba2c468c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>e8fabd7b-8019-4ec5-88a4-5500e5b80a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'element2']</value>
      <webElementGuid>531ad53d-79b6-405d-a017-4a57e4142b1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
