<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_pYour browser does not support iframes. Please update your browser.p</name>
   <tag></tag>
   <elementGuidId>5046280b-c627-44b5-a940-eee0c08e6759</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ts-iframe']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>31811891-3a2d-4a4b-8839-691f43bcbc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7f880229-7f65-4972-a6af-1a03e9c780a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>faac5a1d-cc1f-4dd1-8bb3-56190f1c62aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8cedd5e8-d4b2-4d35-9bd6-01a21e7fc7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>javascript: $('#preloader').hide();</value>
      <webElementGuid>8cf31bb3-82cb-4a8f-853c-4b257c95184d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sos.preprod.simpligov.com/preprod/Portal/ShowWorkFlow/AnonymousEmbed/d23d2199-dd9b-4bef-9f37-ce39a02fd800</value>
      <webElementGuid>6d2374d5-e100-45e2-8b72-2bc0b8dc88f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        &lt;p>Your browser does not support iframes. Please update your browser.&lt;/p>
    </value>
      <webElementGuid>0bec441a-db91-43c2-a5a4-3c0761f11816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ts-iframe&quot;)/iframe[1]</value>
      <webElementGuid>e3a0a908-d153-4364-8a31-8bdd70e752b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ts-iframe']/iframe</value>
      <webElementGuid>893b040e-6ef1-45b3-91cd-4705c63ebdd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::iframe[1]</value>
      <webElementGuid>0542251f-195b-4bf0-9122-170599e563f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/following::iframe[1]</value>
      <webElementGuid>fdfdb340-4561-491a-8237-100c5b94206f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show or Hide'])[1]/preceding::iframe[1]</value>
      <webElementGuid>20658760-4bea-4695-aea8-3b9e4dca13b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;p>Your browser does not support iframes. Please update your browser.&lt;/p>']/parent::*</value>
      <webElementGuid>8ef0e300-f911-4c4f-acd0-d0108f6e517d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8c98b53d-c7f8-4dfb-a7ab-091218b34eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://sos.preprod.simpligov.com/preprod/Portal/ShowWorkFlow/AnonymousEmbed/d23d2199-dd9b-4bef-9f37-ce39a02fd800' and (text() = '
        &lt;p>Your browser does not support iframes. Please update your browser.&lt;/p>
    ' or . = '
        &lt;p>Your browser does not support iframes. Please update your browser.&lt;/p>
    ')]</value>
      <webElementGuid>658e5fd6-ab38-488d-9825-79d8d0b4e81a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
