<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Owner (Registrant)_element5</name>
   <tag></tag>
   <elementGuidId>6f4cd998-eea6-4a60-9e9b-02ff3a34130e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#element5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79ccf93f-8ea3-40be-a041-2cf6df678675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>594381d4-f5c6-4a48-80c0-b4f726a1b390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>35428a4e-a49a-470f-a624-8b03be5c3aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withQTip toCheck requiredCustom input-text textfield  condition-trigger show-character-count tooltipstered valid</value>
      <webElementGuid>cc16b511-7759-4383-a51e-c3ff70ac5436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-name</name>
      <type>Main</type>
      <value>element5</value>
      <webElementGuid>f1ec643d-1870-4420-914e-bea8bd195a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element5</value>
      <webElementGuid>fa25e4f8-7dcb-4c14-82fd-11fa0433cb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>249</value>
      <webElementGuid>4111bf2d-2c15-4968-853c-209f9e06661c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>element5</value>
      <webElementGuid>cd09bd38-784f-415a-b989-e7fdd2a971d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CalculateFormula(this);</value>
      <webElementGuid>cda5de67-1651-42c6-a152-0601e65b554f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>66bc72c0-85c3-49af-887d-85cc68c6dae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>12839551-9890-4e5e-b842-9f38b1df2132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0fc20350-79d8-4f96-912e-aaedd732677c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldtitle</name>
      <type>Main</type>
      <value>Enter the complete name of Owner (Registrant). Enter the name of the business entity or the name(s) of the individual(s).</value>
      <webElementGuid>42318227-9a2f-45aa-a6e4-1e1aff035d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5466839e-7a84-40c0-badb-e96b7a37e08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>d99f32d7-6d28-435e-b832-52bb1fda0dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-14</value>
      <webElementGuid>b7a35824-c1f5-4483-b68e-19744a4b2e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element5&quot;)</value>
      <webElementGuid>a1de8cdc-adbf-4cfd-89c2-755892b69838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MAnualmodecapture/Page_TrademarkTrademark Online Filing  California Secretary of State/iframe_pYour browser does not support iframes. Please update your browser.p</value>
      <webElementGuid>ade1b80c-df87-4a6f-a63f-3d36a97812da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element5']</value>
      <webElementGuid>91c6d62f-1481-4f10-b5cc-f167f2d72705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-element-wrapper_5']/div/div[2]/input</value>
      <webElementGuid>fed60691-240a-4d6c-8a71-6507fda6c7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>96d2999a-3d88-46f6-8d61-7991aec5e6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'element5' and @name = 'element5' and @type = 'text']</value>
      <webElementGuid>f85bd1e3-5bfa-47c7-818a-1c951f1f9417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
