<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radiobutton for Trademark</name>
   <tag></tag>
   <elementGuidId>d312527d-2b60-4623-803e-337749c0da3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element70_Trademark']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#element70_Trademark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0065d65-8985-43ef-a1c6-e0f064aca755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>315cb688-7011-41a2-87d9-0ad004020b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Trademark</value>
      <webElementGuid>50bde208-b2b6-40fc-bfa8-bdb1afb36430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element70_Trademark</value>
      <webElementGuid>5677c862-0b81-4425-9b7f-2b8a93f11c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>element70</value>
      <webElementGuid>a6a6d5e8-74bf-4e12-9994-f21400969e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-name</name>
      <type>Main</type>
      <value>element70</value>
      <webElementGuid>1a4123fe-485c-4444-9f19-b301daf942a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withQTip toCheck form-element-wrapper radio-button requiredCustom align-block add-to-repository condition-trigger</value>
      <webElementGuid>a14fc036-8a45-442c-905a-135dc6b0fdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4.1</value>
      <webElementGuid>6281db02-863f-4bee-973c-d4e19a54b8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CalculateFormula(this);</value>
      <webElementGuid>3ed23540-745f-4ed8-9ff1-f81ddcd442ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7b1d136d-5818-4b56-85e1-283e422c0725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldtitle</name>
      <type>Main</type>
      <value>Check the appropriate field: Trademark or Service Mark</value>
      <webElementGuid>e7d2673e-eb3b-4d13-8bc6-3d386c6221c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>da97ff48-9d10-40f4-910f-f12bf87a122c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-10</value>
      <webElementGuid>3ffaa493-ded4-4501-8342-d41140bdde07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element70_Trademark&quot;)</value>
      <webElementGuid>5b0aed04-c714-4bb1-a114-26c68144f060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MAnualmodecapture/Page_TrademarkTrademark Online Filing  California Secretary of State/iframe_pYour browser does not support iframes. Please update your browser.p</value>
      <webElementGuid>54ee538d-f647-4a42-9c74-2d48b2bdd8a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element70_Trademark']</value>
      <webElementGuid>45f2a7e6-ed5b-44d8-8a00-794b540feec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-element-wrapper_70']/div/div[2]/div/fieldset/div/div/input</value>
      <webElementGuid>a8d38458-bd3e-4cfb-90fb-44e298ffd5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>481ac8c9-b21b-4933-9bf0-c9e15417543a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'element70_Trademark' and @name = 'element70']</value>
      <webElementGuid>5fb4f795-78b4-46ad-8c22-5e344f109210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
