<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Registration for_element70</name>
   <tag></tag>
   <elementGuidId>d64708df-cac4-4243-8c27-6ae800dfdbe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element70_Trademark']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#element70_Trademark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcf7dac1-9341-4cb5-94fc-1f7f2b54033d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6ade1fc9-6f9a-4711-8d00-a9189c877c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Trademark</value>
      <webElementGuid>610da1eb-a7fd-4741-932c-6fe8d73ee549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element70_Trademark</value>
      <webElementGuid>fdbd41ab-f12e-4c40-bdf4-6ea10065a62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>element70</value>
      <webElementGuid>d82d3f5f-7c02-436e-91e8-63c62a472b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-name</name>
      <type>Main</type>
      <value>element70</value>
      <webElementGuid>e9c5ee5a-daf1-4a5e-92f5-0f0169e80e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>withQTip toCheck form-element-wrapper radio-button requiredCustom align-block add-to-repository condition-trigger</value>
      <webElementGuid>27c8acdd-db07-47b7-8170-9f4ba79ebbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4.1</value>
      <webElementGuid>f3bbf6ef-5fa7-4f33-a115-32b64cf6a4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CalculateFormula(this);</value>
      <webElementGuid>571f0a96-bf97-4f26-9ac7-cd69d78ae177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2332b097-9f18-460b-ba12-e8d8948a7365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldtitle</name>
      <type>Main</type>
      <value>Check the appropriate field: Trademark or Service Mark</value>
      <webElementGuid>1500481e-1be3-46e8-9e97-3ae08ff3ac9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hasqtip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a1adfda2-b64f-4984-99ad-412037fd5e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>qtip-10</value>
      <webElementGuid>7ae9e365-c56a-45c9-a3db-80936ba9f324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element70_Trademark&quot;)</value>
      <webElementGuid>7e40f06b-6571-4469-bbc0-5af4d5324171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_TrademarkTrademark Online Filing  Cali_32bac1/iframe_pYour browser does not support ifram_aa4ea2</value>
      <webElementGuid>45442675-c736-40c8-a4fa-89817c364aa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element70_Trademark']</value>
      <webElementGuid>9e78d234-cdb7-47d2-8d61-c111fcb7fd82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-element-wrapper_70']/div/div[2]/div/fieldset/div/div/input</value>
      <webElementGuid>ea63a2a3-c2b7-4c69-9116-b472cc961d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>ec2d5753-b5a2-4314-867a-79bf86e88e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'element70_Trademark' and @name = 'element70']</value>
      <webElementGuid>9e927703-c0ff-4b26-8743-84ab33fc6629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
