<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_START</name>
   <tag></tag>
   <elementGuidId>94f0dc4a-0585-44cf-ba00-1ff8761be040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnStart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnStart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07155c7f-1187-4b69-a451-47370bde8c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnStart</value>
      <webElementGuid>05f59207-211e-41c3-bb9e-02d642430db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnStart</value>
      <webElementGuid>12343928-eff4-4625-95f0-a9b9794d7363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>03e4facb-66b5-497c-bac5-96fbfc494561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>637c5505-2fa9-4030-8c6b-d6f7d09a70e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href ='/Registration/Home/Trademark' </value>
      <webElementGuid>1c60de8c-9a9d-48ea-bb91-f140dfed9a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>START</value>
      <webElementGuid>c8e6ede9-0fe8-40b1-a8f2-414a47a317cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnStart&quot;)</value>
      <webElementGuid>43ff8346-488d-4c40-bc32-9c441a803090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnStart']</value>
      <webElementGuid>400de469-1262-418d-b502-e0ac8fac685d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='column1']/div/div[6]/div/button</value>
      <webElementGuid>634e0072-120f-488b-897b-2849a0908459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='START'])[1]/following::button[1]</value>
      <webElementGuid>a2727923-1957-4264-9030-f8b4faf84bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='click on the Start button below.'])[1]/following::button[1]</value>
      <webElementGuid>fda982e4-fb20-4e26-b22f-d1f6e99a74ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modification of Registration'])[1]/preceding::button[1]</value>
      <webElementGuid>80fc0244-8809-4e8b-8361-6c716f61430d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment of Trademark/Service Mark (TM-108)'])[1]/preceding::button[1]</value>
      <webElementGuid>79824842-2c5d-4feb-837e-f4b9587177b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>872d6589-e2cb-4f2c-8466-dea845c3448c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnStart' and @name = 'btnStart' and @type = 'submit' and (text() = 'START' or . = 'START')]</value>
      <webElementGuid>fef4d37c-ef63-4da8-897f-352ad9adff43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
